bot:
  token:
  botName:
  botUri:

server:
  port:

spring:
  rabbitmq:
    port:
    host:
    notification:
      queue: notification_queue
      exchange: pdd_exam_exchange
      routingKey: notification_key